# Generated by Django 2.2.10 on 2021-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_entry_model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.CharField(max_length=200)),
                ('stock_index', models.CharField(max_length=200)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('yaxis_type', models.CharField(max_length=20)),
            ],
        ),
    ]
