# Generated by Django 2.2.10 on 2021-04-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_can_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_excel', models.FileField(upload_to='ccanport/%Y/%m/%d')),
                ('benchmark', models.CharField(max_length=200)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('yaxis_type', models.CharField(max_length=20)),
            ],
        ),
    ]
